name: build docker image and upload to cloud

env:
  DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
  DB_SERVER_NAME: ${{ secrets.DB_SERVER_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build -t schwech7/youtubemodel

      - name: Push Docker Image
        run: docker push schwech7/youtubemodel:latest
